services:
  homepage:
    image: thuleseeker/thule:latest
    container_name: thule-homepage
    ports:
      - "8000:8000"
    volumes:
      - thule-data:/app/backend
    restart: unless-stopped

volumes:
  thule-data:
